name: dart_edge_supabase_playground
description: A Supaabase Edge Functions example written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.6
  edge_http_client: ^0.0.1+1
  http: ^0.13.5
  supabase: ^1.6.4
  supabase_functions: ^0.0.2+1

dev_dependencies:
  lints: ^2.1.0